beancount/beanquery

- .github/workflows/checks.yaml
For now we are running it only on one file, that does not have any
violations. We will enable more files as we fix the existing violations.
Refs #8.
> Add github actions for pylint

- beanquery/query_env.py
Using the BQL meta() function is the query FROM clause does not make
much sense as there are no posting to operate on in this context, only
entries, but raising an exception does not seem useful. Make meta()
simply return None in this context.
> Fix meta() BQL function when used in the FROM clause

- beanquery/shell.py
The condition on the output being the standard output was
reversed. Use the opportunity to simplify the code to avoid similar
issues in the future.
> Fix redirection to the pager when evaluating a PRINT query.

- .pylintrc
- beanquery/query_compile_test.py
- beanquery/query_env.py
- beanquery/query_env_test.py
Use a function decorator to build the function evaluator class and add the implementation to the BQL functions registry.
I haven't converted all BQL function definitions yet. It is tedious enough work that I would like to get feedback before converting the remaining ones. The data types are now passed explicitly to the decorator. They could be extracted from type annotations, but the code would not get shorter, and given the uncertain of the annotations implementation in future Python versions I would avoid to interact directly with them.
> Refactor implementation of BQL functions

- beanquery/query_parser.py
Digits following the first character are allowed in SQL ids and there
is no reason why they should not be allowed in BQL too.
> Allow digits in BSL identifiers

- beanquery/query_compile.py
- beanquery/query_compile_test.py
- beanquery/query_execute_test.py
- beanquery/types.py
On one hand this is cool because it extends type checking in BQL resulting in query compile time errors rather than in runtime splats. On the other hand, metadata values are not types, and they cannot reasonably be. Therefore, this requires rewriting something like:
```
SELECT * WHERE entry_meta('foo') > 42
```
into
```
SELECT * WHERE decimal(entry_meta('foo')) > 42
```
Where `decimal` is a type casting function that need to be introduced along with similar type casting functions for all BQL types. Alternatively, the query compiler could in principle infer the type and introduce an implicit type conversion. I am not sure how complex this would turn out to be.
> Refactor binary ops

- .github/workflows/checks.yaml
- .github/workflows/test.yaml
In this context pytest does not offer any advantage and getting rid of the dependency speeds up the jobs a tiny bit.
> Switch from pytest to plain unittest for the CI jobs

- beanquery/query_compile.py
- beanquery/query_compile_test.py
- beanquery/query_execute.py
- beanquery/query_execute_test.py
- beanquery/query_parser.py
- beanquery/query_parser_test.py
The implementation was broken and incomplete. It is not clear what to
do when two columns in the results set contain two inventory columns.
The FLATTEN query option also partially overlaps with the "expand"
option in the table renderer. It has been broken for quite some time
and there have not been many complaints. Just nuke it. If someone
comes up with a sensible design it will be easy to reinstate it.
> Remove partial support for the FLATTEN query option

- beanquery/query_render.py
- beanquery/query_render_test.py
The assumptions in the former implementation were too simplistic and
caused positions with the same units commodity but different costs to
be lost. Give up on the nice tabular format when there are too many
distinct positions to be rendered. In this case the estimated column
width becomes really a worst case estimate and unnecessary trailing
whitespace may be present. The only way to fix this properly would be
a three pass rendering algorithm. However fixing a cosmetic issue in a
table that is going anyhow to do not look neat is not worth the cost.
> render: Fix inventory renderer

- beanquery/query_compile.py
- beanquery/query_compile_test.py
- beanquery/query_execute.py
- beanquery/query_execute_test.py
- beanquery/query_parser.py
- beanquery/query_parser_test.py
So far it handles only one column more than the two pivot columns, ie only the first part of the functionality described in #94
> Implement PIVOT BY cluase

- beanquery/query_compile.py
- beanquery/query_compile_test.py
- beanquery/query_env.py
This generalizes and improves what was previously done only for the
negation operator. Applying this to functions requires marking
functions that depend on the context and do not apply the optimization
to these.
> compile: Implement constants folding

- beanquery/parser/__init__.py
- requirements.txt
- setup.cfg
With the support for #"..." date literals removed, there are no more uses.
> Drop python-dateutil dependency

- beanquery/parser/__init__.py
- beanquery/parser/bql.ebnf
- beanquery/parser/parser.py
- beanquery/shell.py
Move default close date implementation for queries stored in the ledger from the query parse to the shell.  This allow to remove the special handling from generic code.
> parser, shell: Revisit default close date implementation

- beanquery/__init__.py
- beanquery/parser/ast.py
- beanquery/query.py
- beanquery/query_compile.py
- beanquery/query_compile_test.py
- beanquery/query_execute_test.py
- beanquery/shell.py
- beanquery/shell_test.py
- beanquery/sources/beancount.py
``beanquery.connect()`` becomes the main entry point. It takes an URI pointing to a data source and returns a Connection() class with an ``execute()`` method that takes a query string and returns the query results.  The only data source scheme defined so far is ``beancount:`` which is expected to be followed by the path to a Beancount ledger.
This continues the effort toward the generalization of beanquery to work with data sources other than beancount and toward an API somehow similar to the Python's DB-API 2.0.
The main entry point of the old API (beanquery.query.run_query() aka beancount.query.run_query() before the project split) is preserved for backward compatibility.  As no other interface was clearly meant as public API, no particular effort has been put in preserving backward …
> Restructure API

- beanquery/query_compile.py
- beanquery/query_execute_test.py
Following the SQL standard, do not raise an exception on division by zero but return NULL instead. This makes the ``safe_div()`` BQL function obsolete.
> env: Return NULL on division by zero

- beanquery/parser/ast.py
- beanquery/parser/bql.ebnf
- beanquery/parser/parser.py
- beanquery/query_compile.py
- beanquery/query_env.py
- beanquery/query_execute_test.py
- beanquery/query_render.py
- beanquery/tables.py
- beanquery/types.py
This allows to deprecate the `entry_meta()` and `meta()` functions:
```
SELECT entry_meta('foo')
```
becomes
```
SELECT entry.meta['foo']
```
This will allow to deprecate and eventually remove some BQL function
that need access to "hidden" context and that do not really belong in
a SQL-like data model.
> Add getitem and getattr

- beanquery/__init__.py
- beanquery/cursor.py
- beanquery/cursor_test.py
- beanquery/numberify.py
- beanquery/numberify_test.py
- beanquery/query.py
- beanquery/query_execute.py
- beanquery/query_execute_test.py
- beanquery/query_render.py
- beanquery/query_render_test.py
- beanquery/query_test.py
- beanquery/shell.py
- beanquery/sources/beancount.py
- beanquery/tests/tables.py
- beanquery/types.py
Implement relevant aspects of the DB-API 2.0 specification.
https://peps.python.org/pep-0249/
The PEP does not provide a strict specification for some aspects of the API. The under-specified aspects are modeled after the sqlite3 and psycopg implementations.
> Implement most of the DB-API 2.0 specification

- beanquery/query_compile.py
- beanquery/query_env.py
- beanquery/query_render.py
- beanquery/query_render_test.py
- beanquery/sources/beancount.py
- beanquery/tables.py
- beanquery/types.py
These will eventually replace the functions now used to access the fields of the beancount objects.
> beancount: Define more structured types

- beanquery/query_env.py
- beanquery/query_env_test.py
These functions need to handle the meta field to be None because transactions inserted by Beancount for pad directives have postings which the meta field set to None instead than to an empty dictionary.
See https://github.com/beancount/beancount/issues/767.
> Fix meta() and any_meta() functions for postings on pad transactions

- .github/workflows/test.yaml
- beanquery/__init__.py
- beanquery/compiler.py
- beanquery/cursor.py
- beanquery/errors.py
- beanquery/parser/__init__.py
- beanquery/parser/ast.py
- beanquery/parser/bql.ebnf
- beanquery/parser/parser.py
- beanquery/parser_test.py
- beanquery/query_compile_test.py
- beanquery/shell.py
Further steps toward DB-API 2.0 compliance. Allow binding query parameters to "%s" positional or "%(name)s" named placeholders.
The parameters are injected as constants nodes into the query execution tree at compile time, thus no escaping (or even the definition of a string representation) for parameters is required.
> parser, compiler, cursor: Implement handling of query parameters

- beanquery/query_env.py
- setup.cfg
Remove indirection via beancount.utils.date_utils. This makes the dependency on python-dateutil explicit and will allow to remove the utility code from Beancount and thus the Beancount dependency on python-dateutil.
The one argument form of the parse_date() BQL function that tries to guess the date format does not seem a great idea. In the future, it should probably be deprecated and removed.
> Use dateutil.parser directly

- beanquery/query_render.py
- beanquery/query_render_test.py
Fixes:
File ".../beanquery/query_render.py", line 548, in <listcomp>
renderers = [RENDERERS[dtype](ctx) for name, dtype in columns]
^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
columns is no longer a tuple but a list of `beanquery.Column` objects. Fix accessors to datatype and name.
> Fix CSV rendering

- beanquery/render/csv.py
- beanquery/render/text.py
- beanquery/shell.py
- pyproject.toml
The supported rendering formats can be extended adding modules exposing a `render()` function in the `beanquery.render` namespace. See the `beanquery.render.text` and `beanquery.render.csv` modules as examples.
> render: Make results set rendering formats extensible

- beanquery/query_compile.py
- beanquery/query_env.py
- beanquery/query_env_test.py
Add `last_day()` function to retrieve the last day of a given month.
Useful for generating monthly reports, when showing e.g. the market value at the end of each month:
```
SELECT year, month,
CONVERT(LAST(balance), 'USD', LAST_DAY(FIRST(year))) AS market_value,
WHERE account ~ '^Assets:'
GROUP BY year, month 
```
> add date_trunc and interval functions

- beanquery/shell.py
Change the "pager" setting to a boolean enabling or disabling pager support. If the $PAGER environment variable is set, output to be paged is piped to the specified program. Otherwise "more" is used. The pager is used only for interactive invocations of bean-query.
Fixes #198.
> shell: Fix pager support

- beanquery/__init__.py
- beanquery/query.py
- beanquery/query_execute_test.py
- beanquery/shell_test.py
- beanquery/sources/beancount.py
This allows to easily pass arguments that cannot easily be serialized as part of the data source string. In particular this allows to remove some special casing of the beancount data source.
> Revisit API to allow arbitrary keyword arguments to connect()

- beanquery/__init__.py
- beanquery/sources/beancount.py
Use the empty string as default data source name: it makes typing a tiny bit easier and reflects what other DB-ABI implementations use.
Mark additional arguments to the attach() function as keyword only.
> Tiny API tweaks

- beanquery/shell.py
libedit uses different initialization strings. Notably, Homebrew's Python uses libedit instead of GNU readline since version 3.11.
> shell: Correctly set up completion on systems using libedit

- beanquery/compiler.py
- beanquery/query_compile.py
- beanquery/query_compile_test.py
- beanquery/query_execute.py
- beanquery/query_execute_test.py
- beanquery/render/beancount.py
- beanquery/shell.py
I'm opening this PR mostly to record some thoughts. What it is implemented here is the bare minimum that would be required to make the `PRINT` statement a special case of `SELECT` with `format` set to `beancount`. This works:
```
.set format beancount
SELECT entry FROM #postings WHERE date > 2024-01-01
```
and prints all transactions in the beancount syntax. Actually, all transactions are printed one for every posting they contain. This could be solved with a `DISTINCT` clause, but entries are not hashable, thus
```
SELECT DISTINCT entry FROM #postings WHERE date > 2024-01-01
```
results in an error. This should probably be solved. Entries can be easily make hashable assuming that they are immutable.
However, when selecting for an account, this already does what is expected when filtering …
> Add "beancount" result set renderer

- .gitignore
This is just to ignore the files generated during build.
> ignore build by-products

- .github/workflows/checks.yaml
- beanquery/query_render.py
- pyproject.toml
- requirements.txt
> pyproject: Adopt License-Expression (PEP 639) 
